### ISSUE TITLE
Failure with latest Microsoft.Azure.StreamAnalytics.CICD 3.0.0

### ISSUE THREAD

**Issue by soniachan** [Fleid/asa.unittest#15]
The latest release seems to be breaking the test scripts
https://www.nuget.org/packages/Microsoft.Azure.StreamAnalytics.CICD/

Can we lock the package to an older version?

```

07-Sep-2020 08:37:54 | VERBOSE: 301 - Update each conf file
-- | --
07-Sep-2020 08:37:55 | VERBOSE: 401 - Run SA in parallel jobs
07-Sep-2020 08:37:56 | VERBOSE: 402 - Waiting for all jobs to end...
07-Sep-2020 08:38:07 | VERBOSE: 403 - Jobs done
07-Sep-2020 08:38:07 | VERBOSE: 501 - Calculating diffs
07-Sep-2020 08:38:08 | [-] ASAHelloWorld.unit-test 30.75s
07-Sep-2020 08:38:08 | ArgumentException: Invalid array passed in, ',' expected. (41): [{"EventId":"1","EventMessage":"Hello"} {"EventId":"2","EventMessage":"World"} {"EventId":"3","EventMessage":"Hello"} {"EventId":"4","EventMessage":"Friends"}]
07-Sep-2020 08:38:08 | at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\asa.unittest\1.0.9\private\Get-AutRunResult.ps1: line 88
07-Sep-2020 08:38:08 | at Get-AutRunResult<Process>, C:\Program Files\WindowsPowerShell\Modules\asa.unittest\1.0.9\private\Get-AutRunResult.ps1: line 63
07-Sep-2020 08:38:08 | at Start-AutRun<Process>, C:\Program Files\WindowsPowerShell\Modules\asa.unittest\1.0.9\public\Start-AutRun.ps1: line 128
07-Sep-2020 08:38:08 | at <ScriptBlock>, C:\Users\syscon\bamboo-agent-home\xml-data\build-dir\HUBCD-HUBWINPR54-SAUT\stream_analytic\ASAHelloWorld.Tests\ASAHelloWorld.Tests.ps1: line 14
07-Sep-2020 08:38:08 | Tests completed in 30.75s
07-Sep-2020 08:38:08 | Passed: 0 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0

```

**Comment by Fleid** [comment]
Hi @soniachan, thanks for the update.

I deployed a hotfix in [release 1.0.10](https://www.powershellgallery.com/packages/asa.unittest/1.0.10) that is hard-coded to get version [2.4.1](https://www.nuget.org/packages/Microsoft.Azure.StreamAnalytics.CICD/2.4.1) of the CICD package instead of the latest.
Let me know if that helps.

I'm looking into what's wrong with 3.0.0 and plan to publish a 1.0.11 release later to support it.

**Comment by Fleid** [comment]
From what I'm getting, the 3.0.0 version of `sa.exe` now outputs records as rows instead of a comma separated list as it did in 2.4.1 and before.
It makes sense in the long run, the previous format was backward, but I need to update the parsing function. 
It should take a day or two. In the meantime, 1.0.10 is the way to go.

**Comment by soniachan** [comment]
@Fleid Thanks! The release 1.0.10 resolves the issue.
To avoid future release of CICD package from breaking the asa.unit module, can we lock the CICD package version for each release?

**Comment by Fleid** [comment]
Excellent idea!
I'll had it to the to-do :)

Thanks again
