### ISSUE TITLE
Test runs do not support higher CICD nuget version

### ISSUE THREAD

**Issue by Tecnova21** [Fleid/asa.unittest#16]
Hello,
For our ASA project, we are using the CICD version 3.0.0. In Start-AutRun I can specify which version should be used but New-AutProject will always download the 2.4.1 version. 

It would be nice to set the version which I need to use for our project in the New-AutProject command.

**Comment by Fleid** [comment]
Hi,

Thanks for the feedback!

As mentioned in issue #15 the output format of sa.exe was changed with release 3.0.0 of the CICD nuget package.
I had in my backlog to update my parsing routine, but since you're actively using it I'll bump up the priority.

I'm not sure I'll make it a parameter though, I have locked release 1.0.10 on CICD 2.4.1, I'm thinking of only supporting CICD 3.0.0 from 1.0.11 onward.

**Comment by Fleid** [comment]
Hi @Tecnova21 
Release [1.0.11](https://www.powershellgallery.com/packages/asa.unittest/1.0.11) was just published on the gallery.
I implemented the new parsing for CICD 3.0.0 and restored the `-asanugetversion` parameter functionality in `Start-AutRun`.
Let me know how it goes!
